# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwxt', '0004_homework_homeworkansower'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(default='homework', max_length=200),
        ),
    ]
