# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jwxt', '0006_remove_homeworkansower_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjectfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Subjectfile', max_length=200)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('description', models.TextField()),
                ('realfile', models.FileField(upload_to='./', verbose_name='File')),
            ],
        ),
        migrations.AlterField(
            model_name='homework',
            name='questionfile',
            field=models.FileField(upload_to='./', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='homeworkansower',
            name='answerfile',
            field=models.FileField(upload_to='./', verbose_name='File'),
        ),
    ]
