# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jwxt', '0007_auto_20170416_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Subjectfile', max_length=200)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('description', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwxt.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Discussreplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('description', models.TextField()),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwxt.Discuss')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwxt.Student')),
            ],
        ),
    ]
