# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 05:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jwxt', '0008_discuss_discussreplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fillintheblank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptiona', models.TextField()),
                ('ansowera', models.CharField(max_length=200)),
                ('ansowerb', models.CharField(max_length=200, null=True)),
                ('ansowerc', models.CharField(max_length=200, null=True)),
                ('descriptionb', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Multiplechoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('choicea', models.CharField(max_length=200)),
                ('choiceb', models.CharField(max_length=200)),
                ('choicec', models.CharField(max_length=200)),
                ('choiced', models.CharField(max_length=200)),
                ('result', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trueorfalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('result', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='discuss',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jwxt.Student'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='discussreplay',
            name='discuss',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jwxt.Discuss'),
        ),
        migrations.AlterField(
            model_name='discussreplay',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jwxt.Student'),
        ),
        migrations.AlterField(
            model_name='discussreplay',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='homeworkansower',
            name='homework',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jwxt.Homework'),
        ),
        migrations.AlterField(
            model_name='homeworkansower',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jwxt.Student'),
        ),
        migrations.AlterField(
            model_name='homeworkansower',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='上传时间'),
        ),
    ]
