# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwxt', '0009_auto_20170416_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='edit_time',
            new_name='update_time',
        ),
    ]
